// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const PREVIEW_VITE_DEV_SERVER_URL: string;
declare const PREVIEW_VITE_NAME: string;

declare const PLAYER_VITE_DEV_SERVER_URL: string;
declare const PLAYER_VITE_NAME: string;
